### ISSUE TITLE
Auctionator+

### ISSUE THREAD

**Issue by deltaone** [NoM0Re/WoW-3.3.5a-Addons#4]
Don't store stacknum into player DB.

FIX:
Auctionator.lua
------------------------------------------------
function Atr_CreateAuction_OnClick ()

	Atr_Memorize_Stacking_If();
	
move call Atr_Memorize_Stacking_If() into begin of function Atr_CreateAuction_OnClick ...

**Comment by NoM0Re** [comment]
hi the addon is backported from [BlueAo](https://forum.warmane.com/member.php?username=BlueAo). I guess best is to contact him on the [Source](https://forum.warmane.com/showthread.php?t=412904&page=10)
