### ISSUE TITLE
Consider adding SUF

### ISSUE THREAD

**Issue by juxuanu** [NoM0Re/WoW-3.3.5a-Addons#5]
https://www.curseforge.com/wow/addons/shadowed-unit-frames/files/435570

This is the official source, I don't know if a backport of later releases that improves upon that 3.3.5 version for WotLK exists. It'd be nice to consider doing so.

**Comment by NoM0Re** [comment]
Added. Thank you 👍

**Comment by juxuanu** [comment]
Pretty cool. Thanks for keeping this repo, it's a good resource 👍
